name: Deploy to Firebase Hosting in Preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
        env:
          PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY: 6LduGDQpAAAAAKaJwFoSmg3UfUlbXvDTNG0cKlwQ
          PUBLIC_NEWT_FORM_URL: https://obi1-dev.form.newt.so/v1/9nx-Z-uxw
      - name: Deploy to preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRJ_VCANHP_FRONT_PRO }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          channelId: preview
